  services:
    mariadb:
      image: mariadb:latest
      container_name: pedalise_mariadb
      environment:
        MARIADB_ROOT_PASSWORD: password
        MARIADB_DATABASE: pedalise
        MARIADB_USER: pedalise
        MARIADB_PASSWORD: password
      ports:
        - "3306:3306"
      restart: always
      volumes:
        - '/database:/var/lib/mysql'