spring:
  application:
    name: Pedalise

  docker:
    compose:
      file: 'pedalise-backend/docker-compose.yaml'
  jpa:
    hibernate:
      ddl-auto: create

cors:
  allowed-origins:
    - 'http://localhost:3000'